apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-87ht
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftgg-tenant/rhtap-demo-app/hacbs-test-project-87ht@sha256:dba20fa2cb92e750a9ff2f23672e423804fadb339f31eb27631e9b8985db1da7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
