apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-87ht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-87ht
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-87ht
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-87ht
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-87ht
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftgg-tenant/rhtap-demo-app/hacbs-test-project-87ht@sha256:16407758b55bf44f520bfb0dc1c683c2fb58d6ba8f596527628255101fbdce97
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
